global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: node
    static_configs:
      - targets:
          - localhost:9100

  - job_name: ray
    file_sd_configs:
      - files:
          - "/tmp/ray/prom_metrics_service_discovery.json"
